[workspace]

resolver = "2"
members = ["chess-core", "clockwork", "uci"]

[workspace.dependencies]

[workspace.package]
authors = ["Pasindu Pramodya "]
edition = "2021"
license = "MIT"
repository = "https://github.com/MasterBrian99/clockwork"
